
services:
  borderpoints-dev:
    build: .
    volumes:
      - ./config:/docker_dev_mount/proj-borderpoints/config
      - ./inputs:/docker_dev_mount/proj-borderpoints/inputs
      - ./outputs:/docker_dev_mount/proj-borderpoints/outputs
      - ./scripts:/docker_dev_mount/proj-borderpoints/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash