
services:
  borderpoints:
    build: .
    volumes:
      - ./config:/docker_mount/proj-borderpoints/config
      - ./inputs:/docker_mount/proj-borderpoints/inputs
      - ./outputs:/docker_mount/proj-borderpoints/outputs
      - ./scripts:/docker_mount/proj-borderpoints/scripts
      - ./object-detector/scripts:/docker_mount/object-detector/scripts
      - ./object-detector/helpers:/docker_mount/object-detector/helpers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash