prepare_ground_truth.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir:
    vectors: outputs/labels_symbol_matching
  initial_image_dir: inputs/plans
  tile_dir: outputs/rgb_images
  border_points_pt: inputs/ground_truth/PL_realite_terrain_20240614/PL_realite_terain_points.shp
  border_points_poly: inputs/ground_truth/PL_realite_terrain_20240614/Realite_terrain_Polygone/PL_realite_terrain_polygones.shp
  tile_suffix: _geo.tif
  convert_images: True


prepare_symbol_classif.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir:
    vectors: outputs/labels_symbol_matching
  initial_image_dir: inputs/plans
  tile_dir: outputs/rgb_images
  border_points_poly: inputs/ground_truth/PL_realite_terrain_20240318/Realite_terrain_Polygone/PL_realite_terrain_polygones.shp
  cadastral_surveying: inputs/ground_truth/PL_realite_terrain_20240614/Shapefile PL_manquants/PL_manquant_BDMO2.shp
  tile_suffix: _geo.tif
  convert_images: False

boxplots.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir: outputs/feature_engineering
  tile_dir: outputs/rgb_images
  image_delimitation: outputs/labels_symbol_matching/GT/GT_pt_polys.gpkg
  tiles: outputs/labels_symbol_matching/tiles.gpkg

test_notebooks.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir: outputs/feature_engineering
  tile_dir: outputs/rgb_images/symbol_images_GT
  image_gpkg: outputs/labels_symbol_matching/GT/GT_pt_polys.gpkg