prepare_whole_tiles.py:
  working_dir: .
  output_dir: 
    vectors: outputs/gpkg_whole_tiles
    tiles: outputs/rgb_images
  initial_image_dir: inputs/plans
  # overlap_info: outputs/formatted_labels/max_point_size.csv
  convert_images: False


generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: /home/gsalamin/Documents/GitHub/proj-borderpoints/outputs
  datasets:
    aoi_tiles: gpkg_whole_tiles/subtiles.gpkg
    image_source:
      type: FOLDER
      location: rgb_images/subtiles
      srs: 2056
  output_folder: detections
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 1800-1900
    version: 1.0
    description: Points limites des anciens plans cadastraux
    contributor: Canton of Fribourg
    url: none
    license:
      name: unknown
      url: unknown
    categories_file: object_detector/category_ids.json


make_detections.py:
  working_directory: outputs/detections
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../model/model_0004749.pth # trained model minimizing the validation loss, monitor via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 0.05       # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05


post_processing.py:
  working_dir: outputs
  input_dir: detections
  output_dir: detections
  subtiles: gpkg_whole_tiles/subtiles.gpkg
  detections:
    oth: oth_detections_at_0dot05_threshold.gpkg
  category_ids_json: category_ids.json
  score: 0.65
  keep_datasets: False