
get_tile_size.py:
  working_dir: .
  output_dir: outputs/tile_analysis
  tiles: outputs/gpkg_whole_tiles/tiles.gpkg
  plan_scales: inputs/plan_scales.xlsx


get_point_bbox_size.py:
  working_dir: .
  output_dir:
    vectors: outputs/formatted_labels
  border_points: inputs/ground_truth/PL_realite_terrain_20240318/PL_realite_ter_ExportFeature_final.shp