
get_tile_size.py:
  working_dir: .
  output_dir: outputs/tile_analysis
  tiles: outputs/gpkg_whole_tiles/tiles.gpkg
  plan_scales: inputs/plan_scales.xlsx


boxplots.py:
  working_dir: outputs/symbol_classification
  output_dir: feature_engineering
  tile_dir: ../instance_segmentation/rgb_images
  image_delimitation: labels_symbol_matching/GT/GT_pt_polys.gpkg
  tiles: labels_symbol_matching/tiles.gpkg


test_notebooks.py:
  working_dir: outputs/symbol_classification
  output_dir: feature_engineering
  tile_dir: ../instance_segmentation/rgb_images/symbol_images_GT
  svm_dir: svm
  image_gpkg: labels_symbol_matching/GT/GT_pt_polys.gpkg
  hog_features: feature_engineering/hog_features.csv
  band_stats: feature_engineering/stats_on_filtered_bands.csv