
prepare_whole_tiles.py:
  working_dir: .
  output_dir: 
    vectors: outputs/gpkg_whole_oth_tiles
  initial_image_dir: inputs/other_plans/subset
  tile_dir: outputs/rgb_oth_images
  cadastral_surveying: outputs/gpkg_whole_oth_tiles/MO_points.gpkg
  # overlap_info: outputs/formatted_labels/max_point_size.csv
  convert_images: False


format_surveying_data.py:
  working_dir: .
  output_dir:
    vectors: outputs/gpkg_whole_oth_tiles
  cadastral_surveying: inputs/MO/BDMO2.gpkg
  tiles: outputs/gpkg_whole_oth_tiles/subtiles.gpkg


generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: /home/gsalamin/Documents/GitHub/proj-borderpoints/outputs
  datasets:
    aoi_tiles: gpkg_whole_oth_tiles/subtiles.gpkg
    image_source:
      type: FOLDER
      location: rgb_oth_images/subtiles
      srs: 2056
  output_folder: detections_oth_maps
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 1800-1900
    version: 1.0
    description: Points limites des anciens plans cadastraux
    contributor: Canton of Fribourg
    url: none
    license:
      name: unknown
      url: unknown
    categories_file: object_detector/category_ids.json


make_detections.py:
  working_directory: outputs/detections_oth_maps
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../model/model_0004749.pth # trained model minimizing the validation loss, monitor via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 0.05       # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05


post_processing.py:
  working_dir: outputs
  input_dir: detections_oth_maps
  output_dir: detections_oth_maps
  subtiles: gpkg_whole_oth_tiles/subtiles.gpkg
  detections:
    oth: oth_detections_at_0dot05_threshold.gpkg
  category_ids_json: category_ids.json
  score: 0.65
  keep_datasets: False


point_matching.py:
  working_dir: outputs
  output_dir: detections_oth_maps
  detections: detections_oth_maps/detected_points.gpkg
  border_points: gpkg_whole_oth_tiles/MO_points.gpkg


check_with_tlm_data.py:
  working_dir: .
  output_dir: outputs/detections
  matched_points: outputs/detections/matched_points.gpkg
  TLM_data:
    file: inputs/TLM_data_FR.gpkg
    layer_flowing_water: fliessgewaesser
    layer_water_bodies: stehendes_gewaesser
    layer_building_footprint: gebaeude_footprint