prepare_ground_truth.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir:
    vectors: outputs/symbol_classification/labels_symbol_matching
  initial_image_dir: inputs/plans
  tile_dir: outputs/rgb_images
  border_points_pt: inputs/ground_truth/PL_realite_terrain_20240614/PL_realite_terrain_points_v240822.shp
  border_points_poly: inputs/ground_truth/PL_realite_terrain_20240614/Realite_terrain_Polygone/PL_realite_terrain_polygones.shp
  tile_suffix: _geo.tif
  convert_images: True

 
prepare_symbol_classif.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir:
    vectors: outputs/symbol_classification/labels_symbol_matching
  initial_image_dir: inputs/plans
  tile_dir: outputs/rgb_images
  border_points_poly: inputs/ground_truth/PL_realite_terrain_20240614/Realite_terrain_Polygone/PL_realite_terrain_polygones.shp
  cadastral_surveying: inputs/ground_truth/PL_realite_terrain_20240614/Shapefile PL_manquants/PL_manquant_BDMO2.shp
  tile_suffix: _geo.tif
  convert_images: False


data_augmentation.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: ../rgb_images/symbol_images_GT
  tile_dir: ../rgb_images/symbol_images_GT


hog.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: feature_engineering
  tile_dir: ../rgb_images/symbol_images_GT


color_treatment.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: feature_engineering
  tile_dir: ../rgb_images/symbol_images_GT
  image_gpkg: labels_symbol_matching/GT/GT_pt_polys.gpkg
  save_extra: True


train_model.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: model_training
  image_gpkg: labels_symbol_matching/GT/GT_pt_polys.gpkg
  hog_features: feature_engineering/hog_features.csv
  band_stats: feature_engineering/stats_on_filtered_bands.csv


train_separated_models.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: model_training/separated_models
  image_gpkg: labels_symbol_matching/GT/GT_pt_polys.gpkg
  hog_features: feature_engineering/hog_features.csv
  band_stats: feature_engineering/stats_on_filtered_bands.csv


optimization.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: optimization
  tile_dir: ../rgb_images/symbol_images_GT
  image_gpkg: labels_symbol_matching/GT/GT_pt_polys.gpkg
  band_stats: feature_engineering/stats_on_filtered_bands.csv


classify_images_in_folder.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: classification
  model_dir: model_training/SVM/augmented_images
  tile_dir: ../rgb_images/symbol_images
  image_info_gpkg: labels_symbol_matching/MO_pt_polys.gpkg
  variance_filter: feature_engineering/variance_filter.pkl


classify_color_and_shapes.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data/outputs/symbol_classification
  output_dir: classification/separated_models
  model_dir: model_training/separated_models/HGBC/augmented_images
  tile_dir: ../rgb_images/symbol_images
  image_info_gpkg: labels_symbol_matching/MO_pt_polys.gpkg
  variance_filter: feature_engineering/variance_filter.pkl