globals:
  original_tile_suffix: _geo.tif
  grid_width_large: 512
  grid_width_small: 256
  overwrite: True
  thresholds:
    max_nodata_large_tiles: 0.5
    max_nodata_small_tiles: 0.5


pct_to_rgb.py:
  working_dir: .
  input_dir: inputs/plans
  output_dir: outputs/rgb_images


prepare_data.py:
  working_dir: .
  output_dir_vectors: outputs/formatted_labels
  output_dir_tiles: outputs/clipped_tiles
  tile_dir: outputs/plans_rgb
  border_points: inputs/ground_truth/PL_realite_terrain_20240318/PL_realite_ter_ExportFeature_final.shp
  bbox: inputs/ground_truth/PL_realite_terrain_box_20240318/PL_realite_ter_ExportFeature_box.shp
  plan_scales: inputs/plan_scales.xlsx
  # overlap_info: outputs/formatted_labels/max_point_size.csv


prepare_whole_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir: outputs/whole_tiles
  tile_dir: outputs/plans_rgb
  plan_scales: inputs/plan_scales.xlsx
  overlap_info: outputs/formatted_labels/max_point_size.csv


generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: outputs
  datasets:
    aoi_tiles: formatted_labels/subtiles.gpkg
    ground_truth_labels: formatted_labels/ground_truth_labels.gpkg
    image_source:
      type: FOLDER
      location: clipped_tiles/subtiles
      srs: 2056
  output_folder: object_detector
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 1800-1900
    version: 1.0
    description: Points limites des anciens plans cadastraux
    contributor: Canton of Fribourg
    url: none
    license:
      name: unknown
      url: unknown
  seed: 1


train_model.py:
  debug_mode: false
  working_directory: outputs/object_detector
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  COCO_files: # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    model_zoo_checkpoint_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml


make_detections.py:
  working_directory: outputs/object_detector
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ./logs/model_0001499.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 0.2       # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05


assess_detections.py:
  working_directory: outputs/object_detector
  datasets:
    ground_truth_labels: ../formatted_labels/ground_truth_labels.gpkg
    image_metadata_json: img_metadata.json
    split_aoi_tiles: split_aoi_tiles.geojson # aoi = Area of Interest
    detections:
      trn: trn_detections_at_0dot05_threshold.gpkg
      val: val_detections_at_0dot05_threshold.gpkg
      tst: tst_detections_at_0dot05_threshold.gpkg
  output_folder: .