globals:
  original_tile_suffix: _geo.tif
  grid_width_large: 512
  grid_width_small: 256
  overwrite: True
  thresholds:
    max_nodata_large_tiles: 0.5
    max_nodata_small_tiles: 0.5


pct_to_rgb.py:
  working_dir: .
  input_dir: inputs/plans
  output_dir: outputs/rgb_images


prepare_data.py:
  working_dir: .
  output_dir_vectors: outputs/formatted_labels
  output_dir_tiles: outputs/clipped_tiles
  tile_dir: outputs/plans_rgb
  border_points: inputs/ground_truth/PL_realite_terrain_20240318/PL_realite_ter_ExportFeature_final.shp
  bbox: inputs/ground_truth/PL_realite_terrain_box_20240318/PL_realite_ter_ExportFeature_box.shp
  plan_scales: inputs/plan_scales.xlsx
  # overlap_info: outputs/formatted_labels/max_point_size.csv


generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: outputs
  datasets:
    aoi_tiles: formatted_labels/tiles.gpkg
    ground_truth_labels: formatted_labels/ground_truth_labels.gpkg
    orthophotos_web_service:
      type: FOLDER
      url: ../inputs/geofer_images/renamed
      srs: 2056
  output_folder: object_detector
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 1800-2000
    version: 1.0
    description: Points limites des anciens plans cadastraux
    contributor: Canton of Fribourg
    url: none
    license:
      name: unknown
      url: unknown


prepare_whole_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/points-limites/02_Data
  output_dir: outputs/whole_tiles
  tile_dir: outputs/plans_rgb
  plan_scales: inputs/plan_scales.xlsx
  overlap_info: outputs/formatted_labels/max_point_size.csv

